# Generated by Django 5.2.12 on 2026-04-03 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('fat_content', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(70.0)], verbose_name='Жирность, %')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Вес, г')),
                ('is_hard', models.BooleanField(verbose_name='Твёрдый')),
                ('has_mold', models.BooleanField(default=False, verbose_name='С плесенью')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу')),
                ('small_wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена мелкого опта')),
                ('small_wholesale_quantity', models.PositiveIntegerField(default=1, verbose_name='От кол-ва для мелкого опта')),
                ('large_wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена крупного опта')),
                ('large_wholesale_quantity', models.PositiveIntegerField(default=10, verbose_name='От кол-ва для крупного опта')),
            ],
            options={
                'verbose_name': 'Сыр',
                'verbose_name_plural': 'Сыры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MilkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип молока')),
            ],
            options={
                'verbose_name': 'Тип молока',
                'verbose_name_plural': 'Типы молока',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('extra_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Дополнительная скидка на заказ (%)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Партия (корзина)',
                'verbose_name_plural': 'Партии (корзины)',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.cart')),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.cheese', verbose_name='Сыр')),
            ],
            options={
                'verbose_name': 'Позиция партии',
                'verbose_name_plural': 'Позиции партии',
            },
        ),
        migrations.AddField(
            model_name='cheese',
            name='milk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheeses', to='catalog.milktype', verbose_name='Тип молока'),
        ),
    ]
