# Generated by Django 5.2.12 on 2026-03-18 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('milk_type', models.CharField(choices=[('cow', 'коровье'), ('goat', 'козье'), ('sheep', 'овечье'), ('buffalo', 'буйволиное')], max_length=20, verbose_name='Тип молока')),
                ('fat_content', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(70.0)], verbose_name='Жирность, %')),
                ('weight', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Вес, кг')),
                ('is_hard', models.BooleanField(verbose_name='Твёрдый')),
                ('has_mold', models.BooleanField(default=False, verbose_name='С плесенью')),
            ],
        ),
    ]
