# Generated by Django 5.2.12 on 2026-04-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип молока')),
            ],
            options={
                'verbose_name': 'Тип молока',
                'verbose_name_plural': 'Типы молока',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cheese',
            options={'ordering': ['name'], 'verbose_name': 'Сыр', 'verbose_name_plural': 'Сыры'},
        ),
        migrations.AlterField(
            model_name='cheese',
            name='milk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheeses', to='catalog.milktype', verbose_name='Тип молока'),
        ),
    ]
